In [1]:
import numpy as np

def mat_elim(A):
    A = A.astype(float)
    E = np.eye(A.shape[0])

    for i in range(A.shape[0]):
        max_index = np.argmax(abs(A[i:, i])) + i
        A[[i, max_index]] = A[[max_index, i]]
        E[[i, max_index]] = E[[max_index, i]]

        for j in range(i+1, A.shape[0]):
            if A[i, i] == 0:
                continue 
            factor = A[j, i] / A[i, i]
            E[j] -= factor * E[i]
            A[j] -= factor * A[i]
    
    return E

print("Case 1 : non-zero pivot")

A = np.array([
   [2, 4, -2],
   [4, 9, -3],
   [-2, -3, 7]
])

print("A =\n", A)

E = mat_elim(A)
print("E =\n", E)

EA = np.round(E @ A, 3)
print("EA =\n", EA)

print("\n")

print("Case 2 : zero pivot")

A = np.array([
    [0, 2, 4],
    [0, 5, 2],
    [7, 4, 5]
])

print("A =\n", A)

E = mat_elim(A)
print("E =\n", E)

EA = np.round(E @ A, 3)
print("EA =\n", EA)



Case 1 : non-zero pivot
A =
 [[ 2  4 -2]
 [ 4  9 -3]
 [-2 -3  7]]
E =
 [[ 0.          1.          0.        ]
 [ 0.          0.5         1.        ]
 [ 1.         -0.33333333  0.33333333]]
EA =
 [[ 4.     9.    -3.   ]
 [ 0.     1.5    5.5  ]
 [-0.    -0.     1.333]]


Case 2 : zero pivot
A =
 [[0 2 4]
 [0 5 2]
 [7 4 5]]
E =
 [[ 0.   0.   1. ]
 [ 0.   1.   0. ]
 [ 1.  -0.4  0. ]]
EA =
 [[ 7.   4.   5. ]
 [ 0.   5.   2. ]
 [ 0.  -0.   3.2]]
